### ISSUE TITLE
Your project is duplicating data

### ISSUE THREAD

**Issue by guilhermejp8** [startingwithseleniumwebdriver/RealTimeReport#11] opened 2017-02-24 14:59 UTC
Hi my friend, your project is duplicating the data, it calls twice the method onTestSuccess , onTestFailure, onTestSkipped .... I need your help. Do you have any solutions?

**Comment by sureshdubey** [comment] 2017-05-09 10:29
me too facing same issue. Pass % is showing as 200%.
Could you please correct it at your end and upload the changes.

![image](https://cloud.githubusercontent.com/assets/16201956/25846722/86c313c8-34d0-11e7-9291-d20d3a90f7f6.png)

**Comment by startingwithseleniumwebdriver** [comment] 2017-06-28 09:13
We are unable to reproduce this issue from our end can anyone(@guilhermejp8, @sureshdubey ) please share your sample project.

**Comment by kmehta30** [comment] 2018-06-06 16:21
@startingwithseleniumwebdriver   I am also facing the same issue of getting 200% pass. Any solution for this..
![image](https://user-images.githubusercontent.com/12829098/41051445-bb7a6514-69e8-11e8-93ca-a5491302ce28.png)

**Comment by rathodamol** [comment] 2018-06-21 07:44
Do you have any update on the said issue.
By the way I am using the BaseTest class which is extended to all the Test Cases

**Comment by startingwithseleniumwebdriver** [comment] 2019-04-26 11:20
The completed percentage is coming more than 100%. The problem was - TestNG captures the excluded `@test` methods list which are not really excluded by user, they are the configuration methods (i.e @BeforeTest etc..). So, now an extra check is applied from our code end to verify whether the `excluded` methods reported by TestNG is `@test` annotated method or not.

And sorry for the delay for the fix - as we could not reproduce the issue. So closing the issue.

**Closed as completed by startingwithseleniumwebdriver** 2019-04-26 11:20 UTC
Labels: duplicate
